version: '3.5'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - ${RABBIT_PORT}:5672
      - ${WEB_RABBIT_MQ}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_LOGIN}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
    env_file:
      - .env
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - protollm_sdk

  redis:
    image: "redis:alpine"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/var/lib/data
    networks:
      - protollm_sdk

  celery_worker:
    build: .
    depends_on:
      - rabbitmq
      - redis
    networks:
      - protollm_sdk
    env_file:
      - .env
    command: celery -A protollm_sdk.celery.app worker --loglevel=info

  flower:
    build: .
    ports:
      - ${FLOWER_PORT}:7672
    depends_on:
      - rabbitmq
      - celery_worker
    networks:
      - protollm_sdk
    env_file:
      - .env
    command: sh -c "sleep 20 && celery -A protollm_sdk.celery.app flower --broker=${CELERY_BROKER_URL} --port=7672"

  server:
    image: chromadb/chroma:latest
    env_file:
      - .env
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - ${VECTOR_PORT}:8000
    networks:
      - protollm_sdk

  embedding_server:
    image: ${EMBEDDING_IMAGE:-ghcr.io/huggingface/text-embeddings-inference:cpu-0.3.0}
    command: --model-id ${EMBEDDING_NAME:-intfloat/multilingual-e5-large} --revision ${EMBEDDING_REVISION:-main}
    ports:
      - "${TEXT_EMB_PORT}:80"
    networks:
      - protollm_sdk
    volumes:
      - hf_cache:/data

volumes:
  rabbitmq_data:
  redis_data:
  hf_cache:

networks:
  protollm_sdk:
    name: protollm_sdk
    driver: bridge
